### ISSUE TITLE
Port to WebExtensions for Firefox

### ISSUE THREAD

**Issue by deltaidea** [vk-x/vk-x#26]
Yay WebExtensions!

https://wiki.mozilla.org/WebExtensions
http://arewewebextensionsyet.com

**Comment by soredake** [comment]
https://github.com/Noitidart/Chrome-Store-Foxified

**Comment by deltaidea** [comment]
So yeah, this is essentially taken care of by Mozilla folks. Just need to publish there or make a note in readme on how to install this in Firefox.

**Comment by deltaidea** [comment]
No longer relevant for me. PRs are welcome.
