### ISSUE TITLE
Enable Home, End, PageUp and PageDown buttons in conversations

### ISSUE THREAD

**Issue by deltaidea** [vk-x/vk-x#28]

**Comment by ghost** [comment]
Yes, **BUT** in start will be _PageUp_ and _PageDown_ in **left side**. In **settings** you can **change** wich _buttons will be used_!

**Comment by deltaidea** [comment]
I'm sorry, what?

**Comment by deltaidea** [comment]
Already implemented by vk.com. If you wait long enough, the problem disappears.
